# Generated by Django 6.0.7 on 2026-07-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='photo',
            field=models.ImageField(blank=True, default='cooks/default.png', null=True, upload_to='cooks/'),
        ),
    ]
