# Generated by Django 6.0.7 on 2026-07-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_cook_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishtype',
            name='image',
            field=models.ImageField(blank=True, upload_to='dish_types/'),
        ),
        migrations.AlterField(
            model_name='cook',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cooks/'),
        ),
    ]
